site_name: OpenQaoa
repo_url: https://github.com/entropicalabs/openqaoa
repo_name: entropicalabs/openqaoa

theme:
  name: material
  icon:
    repo: fontawesome/brands/github 
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


plugins:
  - search

extra_css:
  - stylesheets/extra.css

nav:
  - OpenQAOA: index.md
  - Features: features.md
  - Getting Started: getting-started.md
  - Workflows: workflows.md