site_name: OpenQAOA
repo_url: https://github.com/entropicalabs/openqaoa
repo_name: entropicalabs/openqaoa
copyright: Copyright &copy; 2022 by Entropica Labs Pte Ltd. All rights reserved.


theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  logo: img/entropica_logo.png
  favicon: img/entropica_logo.png
  language: en 
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.sections
    - navigation.footer
    - toc.integrate

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true


nav:
  - OpenQAOA: index.md
  - Features: features.md
  - What is the QAOA?: what-is-the-qaoa.md
  - Getting Started: 
      - install-openqaoa.md
      - the-simplest-workflow.md
      - making-sense-of-the-result.md
  - Workflows:
      - customise-the-QAOA-workflow.md
      - recursive-qaoa.md
  - Parametrizations:
      - parametrization/parametrization.md
      - parametrization/standard-parametrization.md
      - parametrization/extended-parametrization.md
      - parametrization/fourier-parametrization.md
  - The devices:
      - devices/device.md
      - Local simulators:
        - devices/entropica-labs-vectorized.md
        - devices/qiskit.md
      - Quantum Processing Units:
        - devices/amazon-braket.md
        - devices/azure-quantum.md
        - devices/ibmq.md
        - devices/rigetti-qcs.md
  - QUBO problems:
      - generic-qubo.md
      - built-in-qubos.md


extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/entropicalabs/openqaoa
  - icon: fontawesome/brands/discord
    link: https://discord.gg/ana76wkKBd
  - icon: fontawesome/brands/medium
    link: https://medium.com/@entropicalabs
    
